10-functions.sh

diff --git a/11-Functions b/11-Functions
--- a/11-Functions
+++ b/11-Functions
@@ -1,10 +1,24 @@
 #! /bin/bash
 
 USERID=$(id -u)
-if [$USERID -ne 0 ]; then
+if [ $USERID -ne 0 ]; then
 echo "please run with the root user "
 exit1 
 fi
 VALIDATE=(){
-    if [$1  -ne 0]; then
+    if [ $1 -ne 0 ]; then
+echo "$1 installation is failure"
+exit 1
+else
+echo "$2 installation is successful"
+fi
 }
+dnf install Nginx -y
+validate $? "installing Nginx"
+
+dnf install nodejs -y
+validate $? "installing nodejs"
+
+dnf install mysql -y
+validate $? "installing mysql"
+fi
